version: '3.8'

services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "database_data:/var/lib/mysql"
    environment:
      MYSQL_PASSWORD: "CHANGE_ME"          # Password for the MariaDB user
      MYSQL_ROOT_PASSWORD: "CHANGE_ME_TOO"  # Root password for MariaDB
      MYSQL_DATABASE: "panel"               # Default database name
      MYSQL_USER: "pterodactyl"             # User for the default database

  cache:
    image: redis:alpine
    restart: always

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - database
      - cache
    volumes:
      - "panel_var:/app/var/"
      - "panel_nginx:/etc/nginx/http.d/"
      - "panel_certs:/etc/letsencrypt/"
      - "panel_logs:/app/storage/logs"
    environment:
      APP_URL: "https://pterodactyl.example.com" # URL for the Pterodactyl panel
      APP_TIMEZONE: "UTC"                        # Timezone for the application
      APP_SERVICE_AUTHOR: "noreply@example.com" # Service author email
      TRUSTED_PROXIES: "*"                      # Trusted proxies for security
      LE_EMAIL: ""                             # Email for Let's Encrypt (if using SSL)
      MAIL_FROM: "noreply@example.com"         # Email from address
      MAIL_DRIVER: "smtp"                       # Mail driver
      MAIL_HOST: "mail"                        # SMTP server address
      MAIL_PORT: "1025"                        # SMTP server port
      MAIL_USERNAME: ""                        # SMTP username
      MAIL_PASSWORD: ""                        # SMTP password
      MAIL_ENCRYPTION: "true"                  # SMTP encryption
      DB_PASSWORD: "CHANGE_ME"                 # Database password
      APP_ENV: "production"                    # Application environment
      APP_ENVIRONMENT_ONLY: "false"            # Restrict environment settings
      CACHE_DRIVER: "redis"                    # Cache driver
      SESSION_DRIVER: "redis"                  # Session driver
      QUEUE_DRIVER: "redis"                    # Queue driver
      REDIS_HOST: "cache"                      # Redis host
      DB_HOST: "database"                     # Database host
      DB_PORT: "3306"                          # Database port

volumes:
  database_data:
  panel_var:
  panel_nginx:
  panel_certs:
  panel_logs:

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
