version: 2
services:
  database:
    image: mariadb:10.5
    environment:
      MYSQL_PASSWORD: "CHANGE_ME"
      MYSQL_ROOT_PASSWORD: "CHANGE_ME_TOO"
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    volumes:
      - type: volume
        name: pterodactyl_database
    networks:
      - default

  cache:
    image: redis:alpine
    networks:
      - default

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        name: pterodactyl_var
      - type: volume
        name: pterodactyl_nginx
      - type: volume
        name: pterodactyl_certs
      - type: volume
        name: pterodactyl_logs
    environment:
      APP_URL: "https://pterodactyl.example.com"
      APP_TIMEZONE: "UTC"
      APP_SERVICE_AUTHOR: "noreply@example.com"
      TRUSTED_PROXIES: "*"
      LE_EMAIL: ""
      MAIL_FROM: "noreply@example.com"
      MAIL_DRIVER: "smtp"
      MAIL_HOST: "mail"
      MAIL_PORT: "1025"
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: "true"
      DB_PASSWORD: "CHANGE_ME"
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
    networks:
      - default

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  pterodactyl_database:
  pterodactyl_var:
  pterodactyl_nginx:
  pterodactyl_certs:
  pterodactyl_logs:
